# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/michael-pro/repos/SGR_test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/michael-pro/repos/SGR_test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/michael-pro/repos/SGR_test/CMakeFiles /Users/michael-pro/repos/SGR_test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/michael-pro/repos/SGR_test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SGR_test

# Build rule for target.
SGR_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SGR_test
.PHONY : SGR_test

# fast build rule for target.
SGR_test/fast:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/build
.PHONY : SGR_test/fast

CommandManager.o: CommandManager.cpp.o

.PHONY : CommandManager.o

# target to build an object file
CommandManager.cpp.o:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/CommandManager.cpp.o
.PHONY : CommandManager.cpp.o

CommandManager.i: CommandManager.cpp.i

.PHONY : CommandManager.i

# target to preprocess a source file
CommandManager.cpp.i:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/CommandManager.cpp.i
.PHONY : CommandManager.cpp.i

CommandManager.s: CommandManager.cpp.s

.PHONY : CommandManager.s

# target to generate assembly for a file
CommandManager.cpp.s:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/CommandManager.cpp.s
.PHONY : CommandManager.cpp.s

DescriptorManager.o: DescriptorManager.cpp.o

.PHONY : DescriptorManager.o

# target to build an object file
DescriptorManager.cpp.o:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/DescriptorManager.cpp.o
.PHONY : DescriptorManager.cpp.o

DescriptorManager.i: DescriptorManager.cpp.i

.PHONY : DescriptorManager.i

# target to preprocess a source file
DescriptorManager.cpp.i:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/DescriptorManager.cpp.i
.PHONY : DescriptorManager.cpp.i

DescriptorManager.s: DescriptorManager.cpp.s

.PHONY : DescriptorManager.s

# target to generate assembly for a file
DescriptorManager.cpp.s:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/DescriptorManager.cpp.s
.PHONY : DescriptorManager.cpp.s

FileManager.o: FileManager.cpp.o

.PHONY : FileManager.o

# target to build an object file
FileManager.cpp.o:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/FileManager.cpp.o
.PHONY : FileManager.cpp.o

FileManager.i: FileManager.cpp.i

.PHONY : FileManager.i

# target to preprocess a source file
FileManager.cpp.i:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/FileManager.cpp.i
.PHONY : FileManager.cpp.i

FileManager.s: FileManager.cpp.s

.PHONY : FileManager.s

# target to generate assembly for a file
FileManager.cpp.s:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/FileManager.cpp.s
.PHONY : FileManager.cpp.s

LogicalDeviceManager.o: LogicalDeviceManager.cpp.o

.PHONY : LogicalDeviceManager.o

# target to build an object file
LogicalDeviceManager.cpp.o:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/LogicalDeviceManager.cpp.o
.PHONY : LogicalDeviceManager.cpp.o

LogicalDeviceManager.i: LogicalDeviceManager.cpp.i

.PHONY : LogicalDeviceManager.i

# target to preprocess a source file
LogicalDeviceManager.cpp.i:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/LogicalDeviceManager.cpp.i
.PHONY : LogicalDeviceManager.cpp.i

LogicalDeviceManager.s: LogicalDeviceManager.cpp.s

.PHONY : LogicalDeviceManager.s

# target to generate assembly for a file
LogicalDeviceManager.cpp.s:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/LogicalDeviceManager.cpp.s
.PHONY : LogicalDeviceManager.cpp.s

MemoryManager.o: MemoryManager.cpp.o

.PHONY : MemoryManager.o

# target to build an object file
MemoryManager.cpp.o:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/MemoryManager.cpp.o
.PHONY : MemoryManager.cpp.o

MemoryManager.i: MemoryManager.cpp.i

.PHONY : MemoryManager.i

# target to preprocess a source file
MemoryManager.cpp.i:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/MemoryManager.cpp.i
.PHONY : MemoryManager.cpp.i

MemoryManager.s: MemoryManager.cpp.s

.PHONY : MemoryManager.s

# target to generate assembly for a file
MemoryManager.cpp.s:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/MemoryManager.cpp.s
.PHONY : MemoryManager.cpp.s

PhysicalDeviceManager.o: PhysicalDeviceManager.cpp.o

.PHONY : PhysicalDeviceManager.o

# target to build an object file
PhysicalDeviceManager.cpp.o:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/PhysicalDeviceManager.cpp.o
.PHONY : PhysicalDeviceManager.cpp.o

PhysicalDeviceManager.i: PhysicalDeviceManager.cpp.i

.PHONY : PhysicalDeviceManager.i

# target to preprocess a source file
PhysicalDeviceManager.cpp.i:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/PhysicalDeviceManager.cpp.i
.PHONY : PhysicalDeviceManager.cpp.i

PhysicalDeviceManager.s: PhysicalDeviceManager.cpp.s

.PHONY : PhysicalDeviceManager.s

# target to generate assembly for a file
PhysicalDeviceManager.cpp.s:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/PhysicalDeviceManager.cpp.s
.PHONY : PhysicalDeviceManager.cpp.s

PipelineManager.o: PipelineManager.cpp.o

.PHONY : PipelineManager.o

# target to build an object file
PipelineManager.cpp.o:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/PipelineManager.cpp.o
.PHONY : PipelineManager.cpp.o

PipelineManager.i: PipelineManager.cpp.i

.PHONY : PipelineManager.i

# target to preprocess a source file
PipelineManager.cpp.i:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/PipelineManager.cpp.i
.PHONY : PipelineManager.cpp.i

PipelineManager.s: PipelineManager.cpp.s

.PHONY : PipelineManager.s

# target to generate assembly for a file
PipelineManager.cpp.s:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/PipelineManager.cpp.s
.PHONY : PipelineManager.cpp.s

RenderPassManager.o: RenderPassManager.cpp.o

.PHONY : RenderPassManager.o

# target to build an object file
RenderPassManager.cpp.o:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/RenderPassManager.cpp.o
.PHONY : RenderPassManager.cpp.o

RenderPassManager.i: RenderPassManager.cpp.i

.PHONY : RenderPassManager.i

# target to preprocess a source file
RenderPassManager.cpp.i:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/RenderPassManager.cpp.i
.PHONY : RenderPassManager.cpp.i

RenderPassManager.s: RenderPassManager.cpp.s

.PHONY : RenderPassManager.s

# target to generate assembly for a file
RenderPassManager.cpp.s:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/RenderPassManager.cpp.s
.PHONY : RenderPassManager.cpp.s

SGR.o: SGR.cpp.o

.PHONY : SGR.o

# target to build an object file
SGR.cpp.o:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/SGR.cpp.o
.PHONY : SGR.cpp.o

SGR.i: SGR.cpp.i

.PHONY : SGR.i

# target to preprocess a source file
SGR.cpp.i:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/SGR.cpp.i
.PHONY : SGR.cpp.i

SGR.s: SGR.cpp.s

.PHONY : SGR.s

# target to generate assembly for a file
SGR.cpp.s:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/SGR.cpp.s
.PHONY : SGR.cpp.s

ShaderManager.o: ShaderManager.cpp.o

.PHONY : ShaderManager.o

# target to build an object file
ShaderManager.cpp.o:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/ShaderManager.cpp.o
.PHONY : ShaderManager.cpp.o

ShaderManager.i: ShaderManager.cpp.i

.PHONY : ShaderManager.i

# target to preprocess a source file
ShaderManager.cpp.i:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/ShaderManager.cpp.i
.PHONY : ShaderManager.cpp.i

ShaderManager.s: ShaderManager.cpp.s

.PHONY : ShaderManager.s

# target to generate assembly for a file
ShaderManager.cpp.s:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/ShaderManager.cpp.s
.PHONY : ShaderManager.cpp.s

SwapChainManager.o: SwapChainManager.cpp.o

.PHONY : SwapChainManager.o

# target to build an object file
SwapChainManager.cpp.o:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/SwapChainManager.cpp.o
.PHONY : SwapChainManager.cpp.o

SwapChainManager.i: SwapChainManager.cpp.i

.PHONY : SwapChainManager.i

# target to preprocess a source file
SwapChainManager.cpp.i:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/SwapChainManager.cpp.i
.PHONY : SwapChainManager.cpp.i

SwapChainManager.s: SwapChainManager.cpp.s

.PHONY : SwapChainManager.s

# target to generate assembly for a file
SwapChainManager.cpp.s:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/SwapChainManager.cpp.s
.PHONY : SwapChainManager.cpp.s

TextureManager.o: TextureManager.cpp.o

.PHONY : TextureManager.o

# target to build an object file
TextureManager.cpp.o:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/TextureManager.cpp.o
.PHONY : TextureManager.cpp.o

TextureManager.i: TextureManager.cpp.i

.PHONY : TextureManager.i

# target to preprocess a source file
TextureManager.cpp.i:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/TextureManager.cpp.i
.PHONY : TextureManager.cpp.i

TextureManager.s: TextureManager.cpp.s

.PHONY : TextureManager.s

# target to generate assembly for a file
TextureManager.cpp.s:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/TextureManager.cpp.s
.PHONY : TextureManager.cpp.s

WindowManager.o: WindowManager.cpp.o

.PHONY : WindowManager.o

# target to build an object file
WindowManager.cpp.o:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/WindowManager.cpp.o
.PHONY : WindowManager.cpp.o

WindowManager.i: WindowManager.cpp.i

.PHONY : WindowManager.i

# target to preprocess a source file
WindowManager.cpp.i:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/WindowManager.cpp.i
.PHONY : WindowManager.cpp.i

WindowManager.s: WindowManager.cpp.s

.PHONY : WindowManager.s

# target to generate assembly for a file
WindowManager.cpp.s:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/WindowManager.cpp.s
.PHONY : WindowManager.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/SGR_test.dir/build.make CMakeFiles/SGR_test.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... SGR_test"
	@echo "... CommandManager.o"
	@echo "... CommandManager.i"
	@echo "... CommandManager.s"
	@echo "... DescriptorManager.o"
	@echo "... DescriptorManager.i"
	@echo "... DescriptorManager.s"
	@echo "... FileManager.o"
	@echo "... FileManager.i"
	@echo "... FileManager.s"
	@echo "... LogicalDeviceManager.o"
	@echo "... LogicalDeviceManager.i"
	@echo "... LogicalDeviceManager.s"
	@echo "... MemoryManager.o"
	@echo "... MemoryManager.i"
	@echo "... MemoryManager.s"
	@echo "... PhysicalDeviceManager.o"
	@echo "... PhysicalDeviceManager.i"
	@echo "... PhysicalDeviceManager.s"
	@echo "... PipelineManager.o"
	@echo "... PipelineManager.i"
	@echo "... PipelineManager.s"
	@echo "... RenderPassManager.o"
	@echo "... RenderPassManager.i"
	@echo "... RenderPassManager.s"
	@echo "... SGR.o"
	@echo "... SGR.i"
	@echo "... SGR.s"
	@echo "... ShaderManager.o"
	@echo "... ShaderManager.i"
	@echo "... ShaderManager.s"
	@echo "... SwapChainManager.o"
	@echo "... SwapChainManager.i"
	@echo "... SwapChainManager.s"
	@echo "... TextureManager.o"
	@echo "... TextureManager.i"
	@echo "... TextureManager.s"
	@echo "... WindowManager.o"
	@echo "... WindowManager.i"
	@echo "... WindowManager.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

