name: SGR autobuild

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: 1.3.283.0
          cache: true

      - name: Cache Homebrew
        id: homebrew-install
        uses: actions/cache@v4
        with:
          path: /home/linuxbrew/.linuxbrew
          key: homebrew-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            homebrew-${{ runner.os }}-
      
      - name: Install Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - if: ${{ steps.homebrew-install.outputs.cache-hit != 'true' }}
        name: Install dependencies
        continue-on-error: true
        run: |
            brew install glfw

      - name: Build project
        run: |
          ./build.sh -r